name: Build JAR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14 (x64)
        uses: actions/setup-java@v1
        with:
          java-version: "14.0.1"
          architecture: x64

      - name: Build with Maven
        run: mvn clean package
      - uses: actions/upload-artifact@v1
        with:
          name: artifact 
          path: target/

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: EncodedAPI
          path: jar/